// @ts-nocheck
// Auto-generated by tauri-specta. DO NOT EDIT.


// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async exportFile(filePath: string, content: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_file", { filePath, content }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getTableInfo(tableName: string) : Promise<Result<TableInfo, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_table_info", { tableName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Simple greeting command for demonstration purposes.
 */
async greet(name: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("greet", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads user preferences from disk.
 * Returns default preferences if the file doesn't exist.
 */
async loadPreferences() : Promise<Result<AppPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves user preferences to disk.
 * Uses atomic write (temp file + rename) to prevent corruption.
 */
async savePreferences(preferences: AppPreferences) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_preferences", { preferences }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Sends a native system notification.
 * On mobile platforms, returns an error as notifications are not yet supported.
 */
async sendNativeNotification(title: string, body: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("send_native_notification", { title, body }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Saves emergency data to a JSON file for later recovery.
 * Validates filename and enforces a 10MB size limit.
 */
async saveEmergencyData(filename: string, data: JsonValue) : Promise<Result<null, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_emergency_data", { filename, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Loads emergency data from a previously saved JSON file.
 * Returns FileNotFound if the file doesn't exist.
 */
async loadEmergencyData(filename: string) : Promise<Result<JsonValue, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_emergency_data", { filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Removes recovery files older than 7 days.
 * Returns the count of removed files.
 */
async cleanupOldRecoveryFiles() : Promise<Result<number, RecoveryError>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_old_recovery_files") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Shows the quick pane window and makes it the key window (for keyboard input).
 */
async showQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Dismisses the quick pane window.
 * On macOS, resigns key window status before hiding to avoid activating main window.
 */
async dismissQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Toggles the quick pane window visibility.
 */
async toggleQuickPane() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_quick_pane") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Returns the default shortcut constant for frontend use.
 */
async getDefaultQuickPaneShortcut() : Promise<string> {
    return await TAURI_INVOKE("get_default_quick_pane_shortcut");
},
/**
 * Updates the global shortcut for the quick pane.
 * Pass None to reset to default.
 */
async updateQuickPaneShortcut(shortcut: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_quick_pane_shortcut", { shortcut }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async loadUser(userId: string) : Promise<Result<User | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_user", { userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveUser(user: User) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_user", { user }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async softDeleteUser(userId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("soft_delete_user", { userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async authenticate(username: string, password: string) : Promise<Result<User | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("authenticate", { username, password }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateUser(userId: string, name: string, email: string, avatarUrl: string | null) : Promise<Result<User, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_user", { userId, name, email, avatarUrl }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePassword(userId: string, currentPassword: string, newPassword: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_password", { userId, currentPassword, newPassword }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async usersGetByIds(ids: string[]) : Promise<Result<User[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("users_get_by_ids", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getAll(filters: FilterState[], columns: string[], sort: SortState | null) : Promise<Result<Product[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_all", { filters, columns, sort }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getById(id: string) : Promise<Result<Product | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_by_id", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async productsGetByIds(ids: string[]) : Promise<Result<Product[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("products_get_by_ids", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async create(company: string, name: string, category: string) : Promise<Result<Product, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create", { company, name, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async update(id: string, company: string, name: string, category: string) : Promise<Result<Product, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update", { id, company, name, category }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async softDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("soft_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getProductsWithStockPaginated(filters: FilterState[], columns: string[], sort: SortState | null, page: number, pageSize: number) : Promise<Result<PaginatedResponse<ProductWithStock>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_products_with_stock_paginated", { filters, columns, sort, page, pageSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async variantsGetAll() : Promise<Result<Variant[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("variants_get_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async variantsGetByProductWithStock(productId: string) : Promise<Result<ProductVariantWithStock[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("variants_get_by_product_with_stock", { productId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async variantsGetById(id: string) : Promise<Result<Variant | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("variants_get_by_id", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async variantsGetByIds(ids: string[]) : Promise<Result<Variant[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("variants_get_by_ids", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async variantsCreate(variant: NewVariant) : Promise<Result<Variant, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("variants_create", { variant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async variantsUpdate(id: string, variant: UpdateVariant) : Promise<Result<Variant, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("variants_update", { id, variant }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async variantsDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("variants_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async warehousesGetAll(filters: FilterState[], columns: string[], sort: SortState | null) : Promise<Result<Warehouse[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("warehouses_get_all", { filters, columns, sort }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async warehousesGetById(id: string) : Promise<Result<Warehouse | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("warehouses_get_by_id", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async warehousesGetByIds(ids: string[]) : Promise<Result<Warehouse[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("warehouses_get_by_ids", { ids }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async warehousesCreate(name: string, location: string) : Promise<Result<Warehouse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("warehouses_create", { name, location }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async warehousesUpdate(id: string, name: string, location: string) : Promise<Result<Warehouse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("warehouses_update", { id, name, location }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async warehousesDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("warehouses_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async warehousesGetPaginated(filters: FilterState[], columns: string[], sort: SortState | null, page: number, pageSize: number) : Promise<Result<PaginatedResponse<Warehouse>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("warehouses_get_paginated", { filters, columns, sort, page, pageSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stockLevelsGetAll() : Promise<Result<StockLevel[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stock_levels_get_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stockLevelsGetByVariant(variantId: string) : Promise<Result<StockLevel[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stock_levels_get_by_variant", { variantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stockLevelsGetByWarehouse(warehouseId: string) : Promise<Result<StockLevel[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stock_levels_get_by_warehouse", { warehouseId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stockLevelsGetByProduct(productId: string) : Promise<Result<StockLevelWithVariant[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stock_levels_get_by_product", { productId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stockLevelsGetByWarehouseWithNames(warehouseId: string) : Promise<Result<StockLevelWithVariant[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stock_levels_get_by_warehouse_with_names", { warehouseId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stockMovementsGetAll() : Promise<Result<StockMovement[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stock_movements_get_all") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stockMovementsGetByVariant(variantId: string) : Promise<Result<StockMovement[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stock_movements_get_by_variant", { variantId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async stockMovementsGetByWarehouse(warehouseId: string) : Promise<Result<StockMovement[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("stock_movements_get_by_warehouse", { warehouseId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createTransfer(variantId: string, productId: string, fromWarehouse: string, toWarehouse: string, quantity: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_transfer", { variantId, productId, fromWarehouse, toWarehouse, quantity }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createPurchase(variantId: string, productId: string, toWarehouse: string, quantity: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_purchase", { variantId, productId, toWarehouse, quantity }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createSale(variantId: string, productId: string, fromWarehouse: string, quantity: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_sale", { variantId, productId, fromWarehouse, quantity }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createAdjustment(variantId: string, productId: string, warehouseId: string, quantity: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_adjustment", { variantId, productId, warehouseId, quantity }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async productsGetByWarehousePaginated(warehouseId: string, page: number, pageSize: number) : Promise<Result<PaginatedResponse<ProductWithStock>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("products_get_by_warehouse_paginated", { warehouseId, page, pageSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async globalSearch(query: string, limit: number, offset: number) : Promise<Result<PaginatedSearchResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("global_search", { query, limit, offset }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async refreshSearchIndex() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("refresh_search_index") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchHistoryList(userId: string, limit: number) : Promise<Result<SearchHistoryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_history_list", { userId, limit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchHistoryRecord(userId: string, query: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_history_record", { userId, query }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchHistoryDelete(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_history_delete", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchHistoryClear(userId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_history_clear", { userId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * Application preferences that persist to disk.
 * Only contains settings that should be saved between sessions.
 */
export type AppPreferences = { theme: string; 
/**
 * Global shortcut for quick pane (e.g., "CommandOrControl+Shift+.")
 * If None, uses the default shortcut
 */
quick_pane_shortcut: string | null; 
/**
 * User's preferred language (e.g., "ar", "en")
 * If None, uses system locale detection
 */
language: string | null }
export type ColumnInfo = { cid: number; name: string; col_type: string; notnull: boolean; dflt_value: string | null; pk: boolean }
export type FilterState = { column_id: string; operator: string; value: JsonValue }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type NewVariant = { product_id: string; sku: string; variant_name: string; uom_id: string; retail_price: number; wholesale_price: number; distribution_price: number }
export type PaginatedResponse<T> = { data: T[]; total_count: number; total_pages: number }
export type PaginatedSearchResult = { data: SearchHit[]; total_count: number; total_pages: number }
export type Product = { id: string; company: string; name: string; category: string; created_at: number | null; updated_at: number | null; deleted_at: number | null }
export type ProductVariantWithStock = { id: string; product_id: string; sku: string; variant_name: string; quantity: number; uom_id: string; retail_price: number; wholesale_price: number; distribution_price: number; created_at: number | null; updated_at: number | null; deleted_at: number | null }
export type ProductWithStock = { id: string; company: string; name: string; quantity: number; category: string }
/**
 * Error types for recovery operations (typed for frontend matching)
 */
export type RecoveryError = 
/**
 * File does not exist (expected case, not a failure)
 */
{ type: "FileNotFound" } | 
/**
 * Filename validation failed
 */
{ type: "ValidationError"; message: string } | 
/**
 * Data exceeds size limit
 */
{ type: "DataTooLarge"; max_bytes: number } | 
/**
 * File system read/write error
 */
{ type: "IoError"; message: string } | 
/**
 * JSON serialization/deserialization error
 */
{ type: "ParseError"; message: string }
export type SearchHistoryEntry = { id: string; user_id: string; query: string; created_at: number | null; count: number }
export type SearchHit = { entity_type: string; id: string; parent_id: string | null; matched_column: string | null; match_title: string; highlighted_title: string; subtitle: string; meta: string | null; rank: number }
export type SortState = { column_id: string; direction: string }
export type StockLevel = { variant_id: string; warehouse_id: string; quantity: number }
export type StockLevelWithVariant = { variant_id: string; variant_name: string; sku: string; warehouse_id: string; quantity: number }
export type StockMovement = { id: string; variant_id: string; product_id: string; from_warehouse_id: string | null; to_warehouse_id: string | null; quantity: number; movement_type: string; created_at: number }
export type TableInfo = { table_name: string; columns: ColumnInfo[] }
export type UpdateVariant = { sku: string | null; variant_name: string | null; uom_id: string | null; retail_price: number | null; wholesale_price: number | null; distribution_price: number | null }
/**
 * User data stored in SQLite
 */
export type User = { id: string; name: string; email: string; role: string; avatar_url: string | null }
export type Variant = { id: string; product_id: string; sku: string; variant_name: string; uom_id: string; retail_price: number; wholesale_price: number; distribution_price: number; created_at: number | null; updated_at: number | null; deleted_at: number | null }
export type Warehouse = { id: string; name: string; location: string; created_at: number | null; updated_at: number | null; deleted_at: number | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
