use tauri_specta::{collect_commands, Builder};

pub fn generate_bindings() -> Builder<tauri::Wry> {
    use crate::commands::{
        db_utils, notifications, preferences, products, quick_pane, recovery, stocks, users,
        variants, warehouses,
    };
    use crate::utils::fs_utils;

    Builder::<tauri::Wry>::new().commands(collect_commands![
        fs_utils::export_file,
        db_utils::get_table_info,
        preferences::greet,
        preferences::load_preferences,
        preferences::save_preferences,
        notifications::send_native_notification,
        recovery::save_emergency_data,
        recovery::load_emergency_data,
        recovery::cleanup_old_recovery_files,
        quick_pane::show_quick_pane,
        quick_pane::dismiss_quick_pane,
        quick_pane::toggle_quick_pane,
        quick_pane::get_default_quick_pane_shortcut,
        quick_pane::update_quick_pane_shortcut,
        users::load_user,
        users::save_user,
        users::delete_user,
        users::authenticate,
        users::update_user,
        users::update_password,
        products::get_all,
        products::get_by_id,
        products::create,
        products::update,
        products::delete,
        variants::variants_get_all,
        variants::variants_get_by_product,
        variants::variants_get_by_id,
        variants::variants_create,
        variants::variants_update,
        variants::variants_delete,
        warehouses::warehouses_get_all,
        warehouses::warehouses_get_by_id,
        warehouses::warehouses_create,
        warehouses::warehouses_update,
        warehouses::warehouses_delete,
        stocks::stock_levels_get_all,
        stocks::stock_levels_get_by_variant,
        stocks::stock_levels_get_by_warehouse,
        stocks::stock_levels_get_by_product,
        stocks::stock_levels_get_by_warehouse_with_names,
        stocks::stock_movements_get_all,
        stocks::stock_movements_get_by_variant,
    ])
}

/// Export TypeScript bindings to the frontend.
/// Run with: cargo test export_bindings -- --ignored
pub fn export_ts_bindings() {
    generate_bindings()
        .export(
            specta_typescript::Typescript::default()
                .header("// @ts-nocheck\n// Auto-generated by tauri-specta. DO NOT EDIT.\n\n"),
            "../src/lib/bindings.ts",
        )
        .expect("Failed to export TypeScript bindings");
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Generate TypeScript bindings file.
    /// This test is ignored by default so it doesn't run in CI.
    /// Run manually with: cargo test export_bindings -- --ignored
    #[test]
    #[ignore]
    fn export_bindings() {
        export_ts_bindings();
        println!("✓ TypeScript bindings exported to ../src/lib/bindings.ts");
    }
}
